inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
